//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Tilesets/Test/Tileset_test/test.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// LDtk Enum for test
/// </summary>
public enum Orientation
{
    Up,
    Down,
    Left,
    Right
}

/// <summary>
/// LDtk Enum for test
/// </summary>
public enum RespawnType
{
    Soft,
    Hard
}