//THIS CODE IS AUTOGENERATED, DO NOT OVERRIDE
[System.Serializable]
public class SceneReference
{
    public string SceneName;
    public SceneReference(string sceneName)
    {
        SceneName = sceneName;
    }
   public override string ToString()   {
       return SceneName;
   }
   public override bool Equals(object obj)
   {
   if (obj.GetType() != typeof(SceneReference)) return false;
   return ((SceneReference)obj).SceneName == SceneName;
   }
   public override int GetHashCode()   {
       return SceneName.GetHashCode();
   }
    //AUTOGENERATED
    public static SceneReference SCENE_world_2 = new SceneReference("world_2");
    public static SceneReference SCENE_world_1 = new SceneReference("world_1");
}

